name: Docker Image CI Dev
on:
  push:
    branches: ["dev"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: VULLPY_DEV

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.VULLPY_DOCKER_USERNAME }}
          password: ${{ secrets.VULLPY_DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t varsubham/vullpy-dev-ci-pipeline:latest .

      - name: Push image
        run: docker push varsubham/vullpy-dev-ci-pipeline:latest
